import type {Config} from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '1.5rem',
          lg: '2rem',
        },
        screens: {
          sm: '100%',
          md: '100%',
          lg: '1024px',
          xl: '1280px',
          '2xl': '1536px',
        },
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        'seguros-headline': ['var(--font-poppins)', 'Poppins', 'sans-serif'],
        'sa-body': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'sa-headline': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'tc-body': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'tc-headline': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'lv-body': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'lv-headline': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        code: ['monospace'],
      },
      colors: {
        livre: {
          primary: '#00C853',
          'primary-hover': '#1FCF75',
          'primary-active': '#00A844',
          secondary: '#1B6B47',
          accent: '#64FFDA',
          'petrol-900': '#0A1F26',
          'petrol-800': '#0F2D35',
          'petrol-700': '#163D47',
          'petrol-600': '#1E4F5A',
          'petrol-500': '#356974',
          'bg-base': '#061419',
          'bg-default': '#0A1F26',
          'bg-elevated': '#0F2D35',
          'bg-surface': '#163D47',
          text: '#F0FFF4',
          muted: 'rgba(255, 255, 255, 0.6)',
          border: '#1E4F5A',
          success: '#10B981',
          error: '#EF4444',
          whatsapp: '#25D366',
        },
        telecom: {
          primary: '#6C3AED',
          'primary-hover': '#5B21B6',
          secondary: '#1E1B4B',
          accent: '#06B6D4',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
          bg: '#FFFFFF',
          surface: '#F8FAFC',
          text: '#0F172A',
          muted: '#64748B',
          border: '#E2E8F0',
        },
        sa: {
          primary: '#0046C0',
          'primary-hover': '#0039A0',
          bg: '#FFFFFF',
          surface: '#F7F8FA',
          text: '#1A1A1A',
          muted: '#6B7280',
          border: '#E8EAED',
        },
        seguros: {
          primary: '#00C853',
          dark: '#061B12',
          secondary: '#0D3D2A',
          accent: '#9FFFCE',
          bg: '#020B07',
          text: '#FFFFFF',
          muted: '#B7C9C0',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        'lv-sm': '8px',
        'lv-md': '12px',
        'lv-lg': '16px',
        'lv-xl': '20px',
        'lv-2xl': '24px',
      },
      boxShadow: {
        'lv-sm': '0 2px 8px rgba(6, 20, 25, 0.50)',
        'lv-md': '0 4px 16px rgba(6, 20, 25, 0.55)',
        'lv-lg': '0 8px 32px rgba(6, 20, 25, 0.60)',
        'lv-glow': '0 0 24px rgba(0, 200, 83, 0.20)',
        'lv-glow-lg': '0 0 40px rgba(0, 200, 83, 0.30)',
        'lv-navbar': '0 4px 12px rgba(6, 20, 25, 0.40)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
