apiVersion: v1
kind: Secret
metadata:
  name: admin-secret-dev
  namespace: lpigreendev
type: Opaque
stringData:
  admin-user: "dev_admin"
  admin-password: "change_me_dev"
  admin-jwt-secret: "change_me_dev_jwt_secret_long_random"
