# API Key para autenticação da API de leads. Gerar valor seguro em produção.
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: phdcrm-dev
type: Opaque
stringData:
  api-key: "qOXKMZmz76NQZQ89rJZeXRqIHM21UzPXp1NCbQj5TaI="
