# Editar as senhas antes de aplicar. Exemplo: kubectl create secret generic mysql-secret -n lpigreen --from-literal=mysql-root-password='xxx' --from-literal=mysql-app-password='yyy' --dry-run=client -o yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lpigreen
type: Opaque
stringData:
  mysql-root-password: "change_me_root"
  mysql-app-password: "change_me_app"
